# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push: # indica que se ejecutara el workflow cuando se haga un push a las ramas main o develop
    branches: ["main", "develop"]
  pull_request: # indica que se ejecutara el workflow cuando se haga un pull request a las ramas main o develop
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout # Para traernos la información del repositorio
        uses: actions/checkout@v7.0.1
      - name: Setup Node.js environment # Para instalar la versión de node que necesitamos
        uses: actions/setup-node@v7.0.0
        with: # indicar que version de node queremos instalar y que cache queremos usar
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci --legacy-peer-deps --no-fund --no-audit # instalar dependencias de node
      - run: npm run lint #correr el linter para ver si hay errores de sintaxis
      - run: npm test # correr los tests del proyecto
      - run: npm run build # compilar el proyecto
